/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import modelDominio.Administrador;
import modelDominio.Usuario;
import view.tablemodel.UsuarioTableModel;

/**
 *  trabalho interdisciplinar
 * @author laura ferreira & gabriel hackenhaar
 */
public class TelaUsuario extends javax.swing.JFrame {
    private UsuarioTableModel usuarioTableModel;
    private Usuario nomeUsuario;
    private Usuario login;
    private Usuario senha;
    private Usuario cpf;
    private Usuario email;
    private Usuario telefone;
    
    /**
     * Creates new form TelaUsuario
     */
    public TelaUsuario() {
        initComponents();
        jLLogo.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBVoltar = new javax.swing.JButton();
        jBNovoUsuario = new javax.swing.JButton();
        jLLogo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTUsuarios = new javax.swing.JTable();
        jTFNome = new javax.swing.JTextField();
        jTFUsuario = new javax.swing.JTextField();
        jTFCpf = new javax.swing.JTextField();
        jTFEmail = new javax.swing.JTextField();
        jTFTelefone = new javax.swing.JTextField();
        jPFSenha = new javax.swing.JPasswordField();
        jBSalvar = new javax.swing.JButton();
        jBExcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Usuário");

        jBVoltar.setBackground(new java.awt.Color(90, 90, 205));
        jBVoltar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jBVoltar.setForeground(new java.awt.Color(255, 255, 255));
        jBVoltar.setText("VOLTAR");
        jBVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBVoltarActionPerformed(evt);
            }
        });

        jBNovoUsuario.setBackground(new java.awt.Color(90, 90, 205));
        jBNovoUsuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jBNovoUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jBNovoUsuario.setText("NOVO");
        jBNovoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBNovoUsuarioActionPerformed(evt);
            }
        });

        jLLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/logo pereira.png"))); // NOI18N

        jTUsuarios.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Usuários"
            }
        ));
        jScrollPane1.setViewportView(jTUsuarios);

        jTFNome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTFNome.setForeground(new java.awt.Color(153, 153, 153));
        jTFNome.setText("Nome completo");
        jTFNome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTFNomeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTFNomeFocusLost(evt);
            }
        });

        jTFUsuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTFUsuario.setForeground(new java.awt.Color(153, 153, 153));
        jTFUsuario.setText("Usuário");
        jTFUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTFUsuarioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTFUsuarioFocusLost(evt);
            }
        });

        jTFCpf.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTFCpf.setForeground(new java.awt.Color(153, 153, 153));
        jTFCpf.setText("CPF");
        jTFCpf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTFCpfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTFCpfFocusLost(evt);
            }
        });

        jTFEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTFEmail.setForeground(new java.awt.Color(153, 153, 153));
        jTFEmail.setText("Email");
        jTFEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTFEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTFEmailFocusLost(evt);
            }
        });

        jTFTelefone.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTFTelefone.setForeground(new java.awt.Color(153, 153, 153));
        jTFTelefone.setText("Telefone");
        jTFTelefone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTFTelefoneFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTFTelefoneFocusLost(evt);
            }
        });

        jPFSenha.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPFSenha.setForeground(new java.awt.Color(153, 153, 153));
        jPFSenha.setText("senhasenha");
        jPFSenha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPFSenhaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPFSenhaFocusLost(evt);
            }
        });

        jBSalvar.setBackground(new java.awt.Color(90, 90, 205));
        jBSalvar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jBSalvar.setForeground(new java.awt.Color(255, 255, 255));
        jBSalvar.setText("SALVAR");
        jBSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalvarActionPerformed(evt);
            }
        });

        jBExcluir.setBackground(new java.awt.Color(90, 90, 205));
        jBExcluir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jBExcluir.setForeground(new java.awt.Color(255, 255, 255));
        jBExcluir.setText("EXCLUIR");
        jBExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBNovoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLLogo))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTFUsuario)
                            .addComponent(jTFCpf)
                            .addComponent(jTFEmail)
                            .addComponent(jPFSenha)
                            .addComponent(jTFTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTFNome))))
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBNovoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTFNome, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTFUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPFSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTFCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTFEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTFTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalvarActionPerformed

        String senha = new String(jPFSenha.getPassword());
        if (!jTFNome.getText().equals("")) {
           String nomeUsuario = jTFNome.getText();
           if(!jTFUsuario.getText().equals("")){
               String login = jTFUsuario.getText();
               if (!senha.equals("")){
                   if (!jTFCpf.getText().equals("")){
                       String cpf = jTFCpf.getText();
                       if (!jTFEmail.getText().equals("")){
                           String email = jTFEmail.getText();
                           if (!jTFTelefone.getText().equals("")){
                               String telefone = jTFTelefone.getText();

                               if(this.login == null) {
                                    Administrador administrador = new Administrador(nomeUsuario, login, senha, cpf, email, telefone, 1);
                                    boolean usuarioExiste = TeatroPereiraCliente.ccont.usuarioExiste(administrador);
                                   if (usuarioExiste == true){
                                        JOptionPane.showMessageDialog(rootPane, "Nome de usuário já existente. Tente outro");
                                        jTFUsuario.grabFocus();
                                   }else {
                                       boolean resultado = TeatroPereiraCliente.ccont.usuarioInserir(administrador);
                                        if (resultado == true){
                                            JOptionPane.showMessageDialog(rootPane, "Usuário inserido com sucesso.");
                                            atualizaTabela();
                                            limpaCampos();
                                        } else {
                                            JOptionPane.showMessageDialog(rootPane, "Erro: usuário não pode ser cadastrado.");
                                        }
                                   }                                    
                               } else {
                                   this.nomeUsuario.setNomeUsuario(nomeUsuario);
                                   this.login.setLogin(login);
                                   this.senha.setSenha(senha);
                                   this.cpf.setCpf(cpf);
                                   this.email.setEmail(email);
                                   this.telefone.setTelefone(telefone);
                                   Administrador administrador = new Administrador(nomeUsuario, login, senha, cpf, email, telefone, 0);
                                   boolean usuarioExiste = TeatroPereiraCliente.ccont.usuarioExiste(administrador);
                                   if (usuarioExiste == true){
                                        JOptionPane.showMessageDialog(rootPane, "Nome de usuário já existente. Tente outro");
                                        jTFUsuario.grabFocus();
                                   }else {
                                       boolean resultado = TeatroPereiraCliente.ccont.usuarioAlterar(administrador);
                                        if(resultado == true) {
                                            JOptionPane.showMessageDialog(rootPane, "Usuário alterado com sucesso.");
                                        } else {
                                            JOptionPane.showMessageDialog(rootPane, "Erro: usuário não pode ser atualizado.");
                                        }
                                   } 
                               }
                           } else{
                               JOptionPane.showMessageDialog(rootPane, "Erro: informe o telefone.");
                           }
                       } else {
                           JOptionPane.showMessageDialog(rootPane, "Erro: informe o email.");
                       }
                   } else {
                       JOptionPane.showMessageDialog(rootPane, "Erro: informe o CPF");
                   }
               } else {
                   JOptionPane.showMessageDialog(rootPane, "Erro: informe a senha.");
               }
           } else{
               JOptionPane.showMessageDialog(rootPane, "Erro: informe o usuário.");
           }
       } else {
           JOptionPane.showMessageDialog(rootPane, "Erro: informe o nome.");
       }
        
    }//GEN-LAST:event_jBSalvarActionPerformed

    private void jBExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBExcluirActionPerformed
        // TODO add your handling code here:
        if (jTUsuarios.getSelectedRow() > 0){
            int resposta = JOptionPane.showConfirmDialog(rootPane,
                    "Deseja realmente excluir o usuário?",
                    "Excluir",
                    JOptionPane.YES_NO_OPTION);
            if (resposta == JOptionPane.YES_OPTION){
                Usuario usuario = usuarioTableModel.getUsuario(jTUsuarios.getSelectedRow());
                
                boolean resultado = TeatroPereiraCliente.ccont.usuarioExcluir(usuario);
                
                if (resultado == true){
                    JOptionPane.showMessageDialog(rootPane, "Usuário excluído com sucesso.");
                    atualizaTabela();
                } else {
                    JOptionPane.showMessageDialog(rootPane,
                            "Erro: usuário não pode ser excluído.",
                            "Erro",
                            JOptionPane.ERROR_MESSAGE);
                }
            }    
        }
    }//GEN-LAST:event_jBExcluirActionPerformed

    private void jBNovoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBNovoUsuarioActionPerformed
        // TODO add your handling code here:
        limpaCampos();
    }//GEN-LAST:event_jBNovoUsuarioActionPerformed

    private void jBVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBVoltarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jBVoltarActionPerformed

    private void jTFNomeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFNomeFocusLost
        if (jTFNome.getText().isEmpty()) {
            jTFNome.setText("Nome completo");
        }
    }//GEN-LAST:event_jTFNomeFocusLost

    private void jTFNomeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFNomeFocusGained
        if (jTFNome.getText().equals("Nome completo")) {
            jTFNome.setText("");
        }
    }//GEN-LAST:event_jTFNomeFocusGained

    private void jTFUsuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFUsuarioFocusGained
        if (jTFUsuario.getText().equals("Usuário")) {
            jTFUsuario.setText("");
        }
    }//GEN-LAST:event_jTFUsuarioFocusGained

    private void jTFUsuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFUsuarioFocusLost
        if (jTFUsuario.getText().equals("Usuário")) {
            jTFUsuario.setText("");
        }
    }//GEN-LAST:event_jTFUsuarioFocusLost

    private void jPFSenhaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPFSenhaFocusGained
        if (new String(jPFSenha.getPassword()).equals("senhasenha")) {
            jPFSenha.setText("");
        }
    }//GEN-LAST:event_jPFSenhaFocusGained

    private void jPFSenhaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPFSenhaFocusLost
        if (new String(jPFSenha.getPassword()).isEmpty()) {
            jPFSenha.setText("senhasenha");
        }
    }//GEN-LAST:event_jPFSenhaFocusLost

    private void jTFCpfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFCpfFocusLost
        if (jTFCpf.getText().isEmpty()) {
            jTFCpf.setText("CPF");
        }
    }//GEN-LAST:event_jTFCpfFocusLost

    private void jTFCpfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFCpfFocusGained
        if (jTFCpf.getText().equals("CPF")) {
            jTFCpf.setText("");
        }
    }//GEN-LAST:event_jTFCpfFocusGained

    private void jTFEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFEmailFocusLost
        if (jTFEmail.getText().isEmpty()) {
            jTFEmail.setText("Email");
        }
    }//GEN-LAST:event_jTFEmailFocusLost

    private void jTFEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFEmailFocusGained
        if (jTFEmail.getText().equals("Email")) {
            jTFEmail.setText("");
        }
    }//GEN-LAST:event_jTFEmailFocusGained

    private void jTFTelefoneFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFTelefoneFocusGained
        if (jTFTelefone.getText().equals("Telefone")) {
            jTFTelefone.setText("");
        }
    }//GEN-LAST:event_jTFTelefoneFocusGained

    private void jTFTelefoneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFTelefoneFocusLost
        if (jTFTelefone.getText().isEmpty()) {
            jTFTelefone.setText("Telefone");
        }
    }//GEN-LAST:event_jTFTelefoneFocusLost

    private void atualizaTabela() {
        ArrayList<Usuario> listaUsuarios = TeatroPereiraCliente.ccont.usuarioLista();

        usuarioTableModel = new UsuarioTableModel(listaUsuarios);
        jTUsuarios.setModel(usuarioTableModel);
    }
    private void limpaCampos(){
        jTFNome.setText("Nome completo");
        jTFUsuario.setText("Usuário");
        jPFSenha.setText("senhasenha");
        jTFCpf.setText("CPF");
        jTFEmail.setText("Email");
        jTFTelefone.setText("Telefone");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBExcluir;
    private javax.swing.JButton jBNovoUsuario;
    private javax.swing.JButton jBSalvar;
    private javax.swing.JButton jBVoltar;
    private javax.swing.JLabel jLLogo;
    private javax.swing.JPasswordField jPFSenha;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFCpf;
    private javax.swing.JTextField jTFEmail;
    private javax.swing.JTextField jTFNome;
    private javax.swing.JTextField jTFTelefone;
    private javax.swing.JTextField jTFUsuario;
    private javax.swing.JTable jTUsuarios;
    // End of variables declaration//GEN-END:variables
}

