/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JOptionPane;
import modelDominio.Usuario;

/**
 *  trabalho interdisciplinar
 * @author laura ferreira & gabriel hackenhaar
 */
public class TelaAlterarUsuario extends javax.swing.JDialog {

    private Usuario usuario;
    
    public TelaAlterarUsuario(Usuario usuario) {
        initComponents();
        this.usuario = usuario;
        
        
        if (this.usuario != null) {
            jTFUsuario.setText(usuario.getLogin());
        }
        
        jTFUsuario.addActionListener(e -> jBAlterar.doClick());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLLogo = new javax.swing.JLabel();
        jTFUsuario = new javax.swing.JTextField();
        jBAlterar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tela Alterar Usuário");

        jLLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/logo pereira.png"))); // NOI18N

        jTFUsuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTFUsuario.setForeground(new java.awt.Color(153, 153, 153));

        jBAlterar.setBackground(new java.awt.Color(90, 90, 205));
        jBAlterar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jBAlterar.setForeground(new java.awt.Color(255, 255, 255));
        jBAlterar.setText("ALTERAR");
        jBAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAlterarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jTFUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(112, 112, 112))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLLogo)
                .addGap(33, 33, 33)
                .addComponent(jTFUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jBAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAlterarActionPerformed
        if(!jTFUsuario.getText().equals("")) {
            String login = jTFUsuario.getText();
            
            this.usuario.setLogin(login);

            boolean usuarioExiste = TeatroPereiraCliente.ccont.usuarioExiste(usuario);
            if(usuarioExiste == true) {
                JOptionPane.showMessageDialog(rootPane, "Erro: nome de usuário já existe, tente outro.");                    
            } else {   
                boolean resultado = TeatroPereiraCliente.ccont.usuarioAlterar(usuario);
                if(resultado == true) {
                    JOptionPane.showMessageDialog(rootPane, "Usuário alterado com sucesso.");
                    dispose();    
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Erro: usuário não pode ser alterado.");
                }
            }    
        } else {
            JOptionPane.showMessageDialog(rootPane, "Erro: informe o nome de usuário.");
        }
        
    }//GEN-LAST:event_jBAlterarActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAlterar;
    private javax.swing.JLabel jLLogo;
    private javax.swing.JTextField jTFUsuario;
    // End of variables declaration//GEN-END:variables
}
