/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.io.UnsupportedEncodingException;
import java.security.NoSuchAlgorithmException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import modelDominio.Hash;
import modelDominio.Usuario;

/**
 *  trabalho interdisciplinar
 * @author laura ferreira & gabriel hackenhaar
 */
public class TelaAlterarSenha extends javax.swing.JDialog {

    private Usuario usuario;
    
    public TelaAlterarSenha(Usuario usuario) {
        initComponents();
        this.usuario = usuario;
        
        jPFSenhaVelha.addActionListener(e -> jPFSenhaNova.requestFocus());
        jPFSenhaNova.addActionListener(e -> jBAlterar.doClick());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLLogo = new javax.swing.JLabel();
        jBAlterar = new javax.swing.JButton();
        jPFSenhaVelha = new javax.swing.JPasswordField();
        jPFSenhaNova = new javax.swing.JPasswordField();
        jLSenhaAtual = new javax.swing.JLabel();
        jLSenhaNova = new javax.swing.JLabel();
        jLConfirmaSenha = new javax.swing.JLabel();
        jPFConfirmaSenha = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tela Alterar Senha");

        jLLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/logo pereira.png"))); // NOI18N

        jBAlterar.setBackground(new java.awt.Color(90, 90, 205));
        jBAlterar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jBAlterar.setForeground(new java.awt.Color(255, 255, 255));
        jBAlterar.setText("ALTERAR");
        jBAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAlterarActionPerformed(evt);
            }
        });

        jPFSenhaVelha.setForeground(new java.awt.Color(153, 153, 153));

        jPFSenhaNova.setForeground(new java.awt.Color(153, 153, 153));

        jLSenhaAtual.setForeground(new java.awt.Color(90, 90, 205));
        jLSenhaAtual.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLSenhaAtual.setText("Senha atual:");

        jLSenhaNova.setForeground(new java.awt.Color(90, 90, 205));
        jLSenhaNova.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLSenhaNova.setText("Nova senha:");

        jLConfirmaSenha.setForeground(new java.awt.Color(90, 90, 205));
        jLConfirmaSenha.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLConfirmaSenha.setText("Confirme senha nova:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLLogo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLSenhaAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPFSenhaVelha, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLSenhaNova, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLConfirmaSenha))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jPFSenhaNova)
                                .addComponent(jPFConfirmaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLLogo)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPFSenhaVelha, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLSenhaAtual))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPFSenhaNova, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLSenhaNova))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPFConfirmaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLConfirmaSenha))
                .addGap(18, 18, 18)
                .addComponent(jBAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAlterarActionPerformed
        
        String senhaVelha = new String(jPFSenhaVelha.getPassword());
        String senhaNova = new String(jPFSenhaNova.getPassword());
        String ConfirmaSenha = new String(jPFConfirmaSenha.getPassword());
        if (!senhaVelha.equals("")){
            if (!senhaNova.equals("")){ 
                if (!ConfirmaSenha.equals("")){
                    if (senhaNova.equals(ConfirmaSenha)){
                        try {
                            String senhaCriptografadaVelha = Hash.encriptar(senhaVelha, "SHA-256");
                            this.usuario.setSenha(senhaCriptografadaVelha);
                            System.out.println("Senha: " + this.usuario.getSenha());
                            String senhaCriptografadaNova = Hash.encriptar(senhaNova, "SHA-256");

                            boolean senhaExiste = TeatroPereiraCliente.ccont.senhaUsuarioExiste(usuario, senhaCriptografadaNova);

                            if (senhaExiste == true){

                                this.usuario.setSenha(senhaCriptografadaNova);
                                JOptionPane.showMessageDialog(rootPane, "Senha alterada com sucesso.");
                                dispose();    

                            } else {
                                JOptionPane.showMessageDialog(rootPane, "Erro ao alterar senha.");
                            }
                        } catch (NoSuchAlgorithmException ex) {
                            Logger.getLogger(TelaAlterarSenha.class.getName()).log(Level.SEVERE, null, ex);
                        } catch (UnsupportedEncodingException ex) {
                            Logger.getLogger(TelaAlterarSenha.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    } else {
                        JOptionPane.showMessageDialog(rootPane, "Erro: as senhas não coincidem.");
                        jPFConfirmaSenha.grabFocus();
                        
                    }    
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Erro: confirme a senha nova.");
                    jPFConfirmaSenha.grabFocus();
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "Erro: informe a nova senha.");
                jPFSenhaNova.grabFocus();
            }                
        } else {
            JOptionPane.showMessageDialog(rootPane, "Erro: informe a senha atual.");
            jPFSenhaVelha.grabFocus();
        }
        
    }//GEN-LAST:event_jBAlterarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAlterar;
    private javax.swing.JLabel jLConfirmaSenha;
    private javax.swing.JLabel jLLogo;
    private javax.swing.JLabel jLSenhaAtual;
    private javax.swing.JLabel jLSenhaNova;
    private javax.swing.JPasswordField jPFConfirmaSenha;
    private javax.swing.JPasswordField jPFSenhaNova;
    private javax.swing.JPasswordField jPFSenhaVelha;
    // End of variables declaration//GEN-END:variables
}
